# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evolitve_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='pub_date',
            new_name='start_date',
        ),
        migrations.AlterField(
            model_name='answer',
            name='votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
