# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evolitve_app', '0002_auto_20170927_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=64, unique=True)),
                ('emso', models.CharField(max_length=255, verbose_name='em\u0161o')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='voters_num',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voter',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evolitve_app.Question'),
        ),
    ]
